-- ---------------------------------------------------------------------------
-- 001 — initial schema (MySQL / MariaDB)
--
-- The MySQL counterpart of ../001_initial_schema.sql. Same tables, same
-- columns, same meaning; the differences below are all forced by the dialect
-- and are worth knowing about before editing either file.
--
--   * bigint GENERATED BY DEFAULT AS IDENTITY  ->  BIGINT AUTO_INCREMENT
--   * timestamptz                              ->  DATETIME holding the same
--     instant PHP would print. inc/db.php pins the session time_zone to PHP's
--     own offset on connect, because DATETIME carries no offset of its own and
--     a mismatch silently skews every displayed time.
--   * jsonb                                    ->  JSON
--   * boolean                                  ->  TINYINT(1). PDO returns 0/1;
--     every read site treats these as truthy/falsy, never `=== true`.
--   * text NOT NULL DEFAULT ''                 ->  VARCHAR(n). A TEXT column
--     cannot take a literal DEFAULT on MySQL before 8.0.13 or on older MariaDB,
--     so anything with a default is sized instead. The lengths match the
--     str_cut() caps the application already enforces, which is where the
--     numbers come from — the database will not accept what the form rejects.
--   * the lower(email) unique index            ->  a _ci collation on the
--     column plus a plain UNIQUE. That is the citext substitute: 'A@b.com' and
--     'a@b.com' collide exactly as they do on PostgreSQL.
--
-- utf8mb4 throughout: the three-byte "utf8" alias truncates emoji and several
-- Indic sequences. utf8mb4_unicode_ci rather than utf8mb4_0900_ai_ci because
-- the latter is MySQL 8 only and this has to run on MariaDB too.
--
-- CHECK constraints are included and are enforced by MySQL 8.0.16+ and
-- MariaDB 10.2+. Older servers parse and ignore them; the application validates
-- the same values regardless, so they are a backstop, not the only guard.
--
-- Identifiers are backticked where they collide with a reserved word (`key`),
-- not double-quoted, so this file also imports cleanly through phpMyAdmin —
-- which does not have the ANSI_QUOTES mode inc/db.php sets at runtime.
-- ---------------------------------------------------------------------------

-- --- Identity ---------------------------------------------------------------

CREATE TABLE users (
    id            BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- Case-insensitive collation IS the uniqueness rule here. Lookups spell it
    -- lower(email) = ? to stay identical to the PostgreSQL path; that skips the
    -- index, which is irrelevant on a table holding a handful of staff logins.
    email         VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(120) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    last_login_at DATETIME     NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY users_email_key (email),
    CONSTRAINT users_status_chk CHECK (status IN ('active', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE roles (
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slug        VARCHAR(64)  NOT NULL,
    label       VARCHAR(60)  NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',

    UNIQUE KEY roles_slug_key (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, role_id),
    KEY user_roles_role_idx (role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Server-side session records, so an admin can revoke a login they no longer
-- trust. PHP's own session store cannot be enumerated or invalidated per-user.
-- Only a hash of the token is stored: a leaked database should not hand over
-- live sessions.
CREATE TABLE admin_sessions (
    id           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    token_hash   VARCHAR(64)  NOT NULL,
    ip           VARCHAR(45)  NOT NULL DEFAULT '',
    user_agent   VARCHAR(500) NOT NULL DEFAULT '',
    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at   DATETIME     NOT NULL,
    revoked_at   DATETIME     NULL,

    UNIQUE KEY admin_sessions_token_key (token_hash),
    KEY admin_sessions_user_idx (user_id),
    CONSTRAINT admin_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Site settings ----------------------------------------------------------

-- Key/value rather than one wide row: the admin renders this generically, and
-- adding a setting should not need a migration.
--
-- `key` is a reserved word in MySQL and is backticked here. The application
-- spells it "key" and turns on ANSI_QUOTES so that one spelling serves both
-- drivers — see inc/db.php.
CREATE TABLE settings (
    `key`      VARCHAR(191)  NOT NULL PRIMARY KEY,
    value      VARCHAR(2000) NOT NULL DEFAULT '',
    type       VARCHAR(20)   NOT NULL DEFAULT 'text',
    label      VARCHAR(200)  NOT NULL DEFAULT '',
    hint       VARCHAR(500)  NOT NULL DEFAULT '',
    group_name VARCHAR(60)   NOT NULL DEFAULT 'general',
    sort_order INT           NOT NULL DEFAULT 0,
    updated_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT        NULL,

    KEY settings_updated_by_idx (updated_by),
    CONSTRAINT settings_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT settings_type_chk CHECK (type IN ('text', 'textarea', 'number', 'bool', 'url', 'email', 'tel'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Leads ------------------------------------------------------------------

-- Mirrors what submit.php already collects and enforces. Lengths match the
-- str_cut() limits there (100 / 30 / 2000) so the database cannot accept
-- something the form would have rejected.
CREATE TABLE leads (
    id             BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    company_name   VARCHAR(100)  NOT NULL,
    contact_number VARCHAR(30)   NOT NULL,
    description    VARCHAR(2000) NOT NULL,
    consent_given  TINYINT(1)    NOT NULL DEFAULT 0,

    -- Context, for attribution. source_page records which page the form was on.
    source_page    VARCHAR(255)  NOT NULL DEFAULT '',
    service_slug   VARCHAR(100)  NOT NULL DEFAULT '',

    -- A salted hash, never the raw address: enough to spot repeat submissions
    -- without storing an identifier we have no reason to keep.
    ip_hash        VARCHAR(64)   NOT NULL DEFAULT '',
    user_agent     VARCHAR(500)  NOT NULL DEFAULT '',

    status         VARCHAR(20)   NOT NULL DEFAULT 'new',
    notes          VARCHAR(4000) NOT NULL DEFAULT '',
    assigned_to    BIGINT        NULL,

    created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    KEY leads_created_idx  (created_at DESC),
    KEY leads_status_idx   (status),
    KEY leads_assigned_idx (assigned_to),
    CONSTRAINT leads_assigned_fk FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT leads_status_chk CHECK (status IN ('new', 'contacted', 'qualified', 'won', 'lost', 'spam'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Insights / blog --------------------------------------------------------

CREATE TABLE posts (
    id            BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slug          VARCHAR(191) NOT NULL,
    title         VARCHAR(255) NOT NULL,
    tag           VARCHAR(60)  NOT NULL DEFAULT '',

    -- excerpt is card copy; meta_desc is the ~155-char description tag. They
    -- are different jobs and the good version of one is rarely the other.
    excerpt       VARCHAR(500) NOT NULL DEFAULT '',
    meta_desc     VARCHAR(200) NOT NULL DEFAULT '',

    -- Sanitised HTML, written by an editor. Never rendered without having gone
    -- through the save-time allow-list.
    --
    -- MEDIUMTEXT with no DEFAULT: an article body outgrows VARCHAR, and a TEXT
    -- family column cannot carry a literal default on every supported server.
    -- Every INSERT in the codebase supplies a body, so nothing relies on one.
    body          MEDIUMTEXT   NOT NULL,

    status        VARCHAR(20)  NOT NULL DEFAULT 'draft',

    -- Editorial dates, not file dates: a deploy rewrites every mtime, and
    -- dateModified that churns on every typo teaches crawlers to ignore it.
    published_at  DATETIME     NULL,
    read_minutes  INT          NOT NULL DEFAULT 5,

    author_id     BIGINT       NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY posts_slug_key (slug),
    KEY posts_published_idx (status, published_at DESC),
    KEY posts_author_idx (author_id),
    CONSTRAINT posts_author_fk FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT posts_status_chk CHECK (status IN ('draft', 'published'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Social proof -----------------------------------------------------------

CREATE TABLE case_studies (
    id             BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    client_name    VARCHAR(120)  NOT NULL DEFAULT '',
    sector         VARCHAR(60)   NOT NULL DEFAULT '',
    problem        VARCHAR(2000) NOT NULL DEFAULT '',
    action         VARCHAR(2000) NOT NULL DEFAULT '',

    -- One evidenceable outcome. metric_value is the headline number
    -- ("+182%"); metric_label is what it measures.
    metric_value   VARCHAR(40)   NOT NULL DEFAULT '',
    metric_label   VARCHAR(120)  NOT NULL DEFAULT '',

    -- 1 until the row holds a real, evidenced result. Renders the orange
    -- PLACEHOLDER badge on the public page while set.
    is_placeholder TINYINT(1)    NOT NULL DEFAULT 1,
    is_published   TINYINT(1)    NOT NULL DEFAULT 1,
    sort_order     INT           NOT NULL DEFAULT 0,

    created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE testimonials (
    id             BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,
    quote          VARCHAR(1000) NOT NULL DEFAULT '',
    author_name    VARCHAR(120)  NOT NULL DEFAULT '',
    author_role    VARCHAR(120)  NOT NULL DEFAULT '',
    author_company VARCHAR(120)  NOT NULL DEFAULT '',

    -- Publishing an attributed quote without permission is a real problem, so
    -- it is a column rather than an assumption. The admin should refuse to
    -- clear is_placeholder while this is 0.
    consent_given  TINYINT(1)    NOT NULL DEFAULT 0,

    is_placeholder TINYINT(1)    NOT NULL DEFAULT 1,
    is_published   TINYINT(1)    NOT NULL DEFAULT 1,
    sort_order     INT           NOT NULL DEFAULT 0,

    created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Pricing ----------------------------------------------------------------

CREATE TABLE bundles (
    id           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name         VARCHAR(60)  NOT NULL,
    sub          VARCHAR(200) NOT NULL DEFAULT '',

    -- Free text, not a numeric: the site currently says "Chat for Pricing",
    -- and "from Rs 25,000" is as valid an answer as a number.
    price_text   VARCHAR(100) NOT NULL DEFAULT 'Chat for Pricing',

    is_featured  TINYINT(1)   NOT NULL DEFAULT 0,
    is_published TINYINT(1)   NOT NULL DEFAULT 1,
    sort_order   INT          NOT NULL DEFAULT 0,

    created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE bundle_points (
    id         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bundle_id  BIGINT       NOT NULL,
    label      VARCHAR(200) NOT NULL,
    sort_order INT          NOT NULL DEFAULT 0,

    KEY bundle_points_bundle_idx (bundle_id, sort_order),
    CONSTRAINT bundle_points_bundle_fk FOREIGN KEY (bundle_id) REFERENCES bundles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Media ------------------------------------------------------------------

CREATE TABLE media (
    id            BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- Randomised on upload. The user's original name is kept only for display —
    -- serving a user-supplied filename is how a .php lands in a served path.
    filename      VARCHAR(191) NOT NULL,
    original_name VARCHAR(200) NOT NULL DEFAULT '',

    mime          VARCHAR(100) NOT NULL,
    bytes         BIGINT       NOT NULL DEFAULT 0,
    width         INT          NULL,
    height        INT          NULL,
    alt           VARCHAR(300) NOT NULL DEFAULT '',

    uploaded_by   BIGINT       NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY media_filename_key (filename),
    KEY media_uploaded_by_idx (uploaded_by),
    CONSTRAINT media_uploaded_by_fk FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Audit ------------------------------------------------------------------

-- Every mutating admin action. before/after are JSON so a diff can be rendered
-- without a column per entity type.
CREATE TABLE audit_log (
    id          BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT      NULL,
    action      VARCHAR(60) NOT NULL,
    entity_type VARCHAR(40) NOT NULL DEFAULT '',
    entity_id   VARCHAR(40) NOT NULL DEFAULT '',
    before_data JSON        NULL,
    after_data  JSON        NULL,
    ip          VARCHAR(45) NOT NULL DEFAULT '',
    created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    KEY audit_log_created_idx (created_at DESC),
    KEY audit_log_entity_idx  (entity_type, entity_id),
    KEY audit_log_user_idx    (user_id),
    CONSTRAINT audit_log_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --- Roles ------------------------------------------------------------------

INSERT INTO roles (slug, label, description) VALUES
    ('admin',  'Administrator', 'Full access, including users, roles and settings.'),
    ('editor', 'Editor',        'Manages content and leads. Cannot manage users or settings.'),
    ('viewer', 'Viewer',        'Read-only access to leads and content.');
