-- ---------------------------------------------------------------------------
-- 001 — initial schema
--
-- Everything the admin panel manages. Content that is currently hardcoded in
-- const arrays in inc/config.php (bundles, trust stats) and in page templates
-- (case studies, testimonials, blog cards) moves here so it can be edited
-- without a deploy.
--
-- Conventions:
--   * identity columns rather than serial — the SQL-standard spelling
--   * timestamptz everywhere; the site is IST but leads can arrive from anywhere
--   * status columns are text + CHECK rather than native enums, because adding
--     a value to a PG enum needs DDL while a CHECK is one migration
--   * is_placeholder drives the existing .is-placeholder CSS badge
--     (css/07-utilities.css) — the orange PLACEHOLDER ribbon now clears itself
--     when real content is saved, instead of needing a developer to edit markup
-- ---------------------------------------------------------------------------

-- --- Identity ---------------------------------------------------------------

CREATE TABLE users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text        NOT NULL,
    password_hash text        NOT NULL,
    name          text        NOT NULL,
    status        text        NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'disabled')),
    last_login_at timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness without the citext extension, which is not
-- installed by default on managed Postgres. Every lookup must use lower(email)
-- to hit this index.
CREATE UNIQUE INDEX users_email_lower_key ON users (lower(email));

CREATE TABLE roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        text NOT NULL UNIQUE,
    label       text NOT NULL,
    description text NOT NULL DEFAULT ''
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Server-side session records, so an admin can revoke a login they no longer
-- trust. PHP's own session store cannot be enumerated or invalidated per-user.
-- Only a hash of the token is stored: a leaked database should not hand over
-- live sessions.
CREATE TABLE admin_sessions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   text        NOT NULL UNIQUE,
    ip           text        NOT NULL DEFAULT '',
    user_agent   text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    revoked_at   timestamptz
);
CREATE INDEX admin_sessions_user_idx ON admin_sessions (user_id);

-- --- Site settings ----------------------------------------------------------

-- Key/value rather than one wide row: the admin renders this generically, and
-- adding a setting should not need a migration.
CREATE TABLE settings (
    key        text        PRIMARY KEY,
    value      text        NOT NULL DEFAULT '',
    type       text        NOT NULL DEFAULT 'text'
               CHECK (type IN ('text', 'textarea', 'number', 'bool', 'url', 'email', 'tel')),
    label      text        NOT NULL DEFAULT '',
    hint       text        NOT NULL DEFAULT '',
    group_name text        NOT NULL DEFAULT 'general',
    sort_order int         NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by bigint      REFERENCES users (id) ON DELETE SET NULL
);

-- --- Leads ------------------------------------------------------------------

-- Mirrors what submit.php already collects and enforces. Lengths match the
-- str_cut() limits there (100 / 30 / 2000) so the database cannot accept
-- something the form would have rejected.
CREATE TABLE leads (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name   varchar(100)  NOT NULL,
    contact_number varchar(30)   NOT NULL,
    description    varchar(2000) NOT NULL,
    consent_given  boolean       NOT NULL DEFAULT false,

    -- Context, for attribution. source_page records which page the form was on.
    source_page    text          NOT NULL DEFAULT '',
    service_slug   text          NOT NULL DEFAULT '',

    -- A salted hash, never the raw address: enough to spot repeat submissions
    -- without storing an identifier we have no reason to keep.
    ip_hash        text          NOT NULL DEFAULT '',
    user_agent     text          NOT NULL DEFAULT '',

    status         text          NOT NULL DEFAULT 'new'
                   CHECK (status IN ('new', 'contacted', 'qualified', 'won', 'lost', 'spam')),
    notes          text          NOT NULL DEFAULT '',
    assigned_to    bigint        REFERENCES users (id) ON DELETE SET NULL,

    created_at     timestamptz   NOT NULL DEFAULT now(),
    updated_at     timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX leads_created_idx  ON leads (created_at DESC);
CREATE INDEX leads_status_idx   ON leads (status);
CREATE INDEX leads_assigned_idx ON leads (assigned_to);

-- --- Insights / blog --------------------------------------------------------

CREATE TABLE posts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          text        NOT NULL UNIQUE,
    title         text        NOT NULL,
    tag           text        NOT NULL DEFAULT '',

    -- excerpt is card copy; meta_desc is the ~155-char description tag. They
    -- are different jobs and the good version of one is rarely the other.
    excerpt       text        NOT NULL DEFAULT '',
    meta_desc     text        NOT NULL DEFAULT '',

    -- Sanitised HTML, written by an editor. Never rendered without having gone
    -- through the save-time allow-list.
    body          text        NOT NULL DEFAULT '',

    status        text        NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'published')),

    -- Editorial dates, not file dates: a deploy rewrites every mtime, and
    -- dateModified that churns on every typo teaches crawlers to ignore it.
    published_at  timestamptz,
    read_minutes  int         NOT NULL DEFAULT 5,

    author_id     bigint      REFERENCES users (id) ON DELETE SET NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX posts_published_idx ON posts (status, published_at DESC);

-- --- Social proof -----------------------------------------------------------

CREATE TABLE case_studies (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name    text    NOT NULL DEFAULT '',
    sector         text    NOT NULL DEFAULT '',
    problem        text    NOT NULL DEFAULT '',
    action         text    NOT NULL DEFAULT '',

    -- One evidenceable outcome. metric_value is the headline number
    -- ("+182%"); metric_label is what it measures.
    metric_value   text    NOT NULL DEFAULT '',
    metric_label   text    NOT NULL DEFAULT '',

    -- true until the row holds a real, evidenced result. Renders the orange
    -- PLACEHOLDER badge on the public page while set.
    is_placeholder boolean NOT NULL DEFAULT true,
    is_published   boolean NOT NULL DEFAULT true,
    sort_order     int     NOT NULL DEFAULT 0,

    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE testimonials (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote          text    NOT NULL DEFAULT '',
    author_name    text    NOT NULL DEFAULT '',
    author_role    text    NOT NULL DEFAULT '',
    author_company text    NOT NULL DEFAULT '',

    -- Publishing an attributed quote without permission is a real problem, so
    -- it is a column rather than an assumption. The admin should refuse to
    -- clear is_placeholder while this is false.
    consent_given  boolean NOT NULL DEFAULT false,

    is_placeholder boolean NOT NULL DEFAULT true,
    is_published   boolean NOT NULL DEFAULT true,
    sort_order     int     NOT NULL DEFAULT 0,

    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- --- Pricing ----------------------------------------------------------------

CREATE TABLE bundles (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text    NOT NULL,
    sub          text    NOT NULL DEFAULT '',

    -- Free text, not a numeric: the site currently says "Chat for Pricing",
    -- and "from Rs 25,000" is as valid an answer as a number.
    price_text   text    NOT NULL DEFAULT 'Chat for Pricing',

    is_featured  boolean NOT NULL DEFAULT false,
    is_published boolean NOT NULL DEFAULT true,
    sort_order   int     NOT NULL DEFAULT 0,

    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE bundle_points (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id  bigint NOT NULL REFERENCES bundles (id) ON DELETE CASCADE,
    label      text   NOT NULL,
    sort_order int    NOT NULL DEFAULT 0
);
CREATE INDEX bundle_points_bundle_idx ON bundle_points (bundle_id, sort_order);

-- --- Media ------------------------------------------------------------------

CREATE TABLE media (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Randomised on upload. The user's original name is kept only for display —
    -- serving a user-supplied filename is how a .php lands in a served path.
    filename      text        NOT NULL UNIQUE,
    original_name text        NOT NULL DEFAULT '',

    mime          text        NOT NULL,
    bytes         bigint      NOT NULL DEFAULT 0,
    width         int,
    height        int,
    alt           text        NOT NULL DEFAULT '',

    uploaded_by   bigint      REFERENCES users (id) ON DELETE SET NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- --- Audit ------------------------------------------------------------------

-- Every mutating admin action. before/after are jsonb so a diff can be rendered
-- without a column per entity type.
CREATE TABLE audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint      REFERENCES users (id) ON DELETE SET NULL,
    action      text        NOT NULL,
    entity_type text        NOT NULL DEFAULT '',
    entity_id   text        NOT NULL DEFAULT '',
    before_data jsonb,
    after_data  jsonb,
    ip          text        NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_created_idx ON audit_log (created_at DESC);
CREATE INDEX audit_log_entity_idx  ON audit_log (entity_type, entity_id);

-- --- Roles ------------------------------------------------------------------

INSERT INTO roles (slug, label, description) VALUES
    ('admin',  'Administrator', 'Full access, including users, roles and settings.'),
    ('editor', 'Editor',        'Manages content and leads. Cannot manage users or settings.'),
    ('viewer', 'Viewer',        'Read-only access to leads and content.');
