-- ---------------------------------------------------------------------------
-- 003 — login throttling
--
-- rate_limit_ok() in inc/security.php is session-keyed, which is the right
-- trade for the public contact form: shared NAT means IP-keying would block a
-- whole office, and the honeypot plus CSRF already stop naive bots.
--
-- It is NOT sufficient for a login. An attacker guessing passwords controls
-- their own cookie jar and simply discards the session between attempts, so a
-- session-keyed counter never increments. Throttling has to persist somewhere
-- the client cannot influence.
--
-- Recorded per (identifier, ip) so that:
--   * many failures against one account lock that account's login path,
--     regardless of where they come from
--   * many failures from one address are caught even when the attacker rotates
--     usernames
-- ---------------------------------------------------------------------------

CREATE TABLE login_attempts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The submitted email, lowercased. Stored even when no such user exists —
    -- that is precisely the case worth rate limiting.
    identifier  text        NOT NULL,
    ip          text        NOT NULL DEFAULT '',
    successful  boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX login_attempts_identifier_idx ON login_attempts (identifier, created_at DESC);
CREATE INDEX login_attempts_ip_idx         ON login_attempts (ip, created_at DESC);

COMMENT ON TABLE login_attempts IS
    'Login throttling. Prune rows older than the longest window; nothing reads them beyond that.';
