-- ---------------------------------------------------------------------------
-- 004 — core team members
--
-- One row per person on the public team page (team.php). The card is a native
-- <details>: collapsed it shows photo + name + role + brief, and the arrow
-- opens it onto the bio and the profile links.
--
-- brief and bio are separate columns on purpose. The closed state is the line
-- a visitor actually reads, so an editor has to be able to write it; deriving
-- it from the first 200 characters of bio would make the teaser a side effect
-- of however paragraph one happened to start.
--
-- The photo is a reference into the existing media library rather than a
-- filename column or a second upload path. admin/media.php is the only upload
-- pipeline in this codebase and it is deliberately strict — generated
-- filenames, sniffed MIME, a getimagesize() check, no SVG (see the comment at
-- the top of that file). A second, laxer path just for headshots would undo
-- all of it.
--
-- ON DELETE SET NULL, not CASCADE: removing an image must not remove the
-- person. The card falls back to the i-user icon.
--
-- No consent_given column, deliberately. testimonials has one because
-- publishing a quote attributed to a third-party client without permission is
-- a legal problem. Team members are our own staff and that conversation is an
-- HR one, not a schema one. What IS carried over is the cheap half of the
-- rule: admin/team.php refuses to publish while the name still contains "[".
-- ---------------------------------------------------------------------------

CREATE TABLE team_members (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name           text    NOT NULL DEFAULT '',
    role           text    NOT NULL DEFAULT '',

    -- Shown while the card is collapsed.
    brief          text    NOT NULL DEFAULT '',
    -- Revealed when the card is opened.
    bio            text    NOT NULL DEFAULT '',

    -- Absolute http(s) only; a relative URL is meaningless for an off-site
    -- profile. Enforced in admin/team.php, which is the only writer.
    github_url     text    NOT NULL DEFAULT '',
    linkedin_url   text    NOT NULL DEFAULT '',

    photo_media_id bigint  REFERENCES media (id) ON DELETE SET NULL,

    sort_order     int     NOT NULL DEFAULT 0,
    is_placeholder boolean NOT NULL DEFAULT true,
    is_published   boolean NOT NULL DEFAULT true,

    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX team_members_photo_idx ON team_members (photo_media_id);

COMMENT ON TABLE  team_members                IS
    'People rendered on team.php. Ordered by sort_order, then id.';
COMMENT ON COLUMN team_members.brief          IS
    'One line, shown while the card is collapsed.';
COMMENT ON COLUMN team_members.bio            IS
    'Full detail, revealed when the card is expanded.';
COMMENT ON COLUMN team_members.photo_media_id IS
    'media.id of the headshot. NULL renders the i-user fallback.';
COMMENT ON COLUMN team_members.is_placeholder IS
    'Renders the orange PLACEHOLDER badge and withholds the Person JSON-LD node.';
