-- ---------------------------------------------------------------------------
-- 007 — blog: categories, cover images and a credited author
--
-- This extends the existing posts table rather than introducing a second
-- article type. What the site calls "Insights" was already a blog in every
-- respect that matters — a posts table, BlogPosting JSON-LD, an admin CMS,
-- /insights/{slug} permalinks — and the CSS classes it renders through were
-- already named .blog-card and .blog-grid. Adding a parallel table would have
-- given the site two article systems and one of them would rot.
--
-- WHAT posts DOES NOT GET
-- The existing `tag` column stays. It is a single free-text label, and it is
-- read by insights.php today; categories supersede it, but dropping a column
-- that public code still selects belongs in its own change, after the
-- rendering has moved over and stayed moved for a release. The backfill at the
-- bottom copies every distinct tag into categories so nothing is lost in the
-- meantime.
--
-- WHY author_team_id RATHER THAN THE EXISTING author_id
-- posts.author_id points at users — whoever was logged in when the row was
-- written. That is an audit fact, not a byline. Who a piece is credited to is
-- an editorial decision (a ghost-written founder post is the obvious case),
-- and team_members already holds the name, role and photo a byline needs.
-- Both columns therefore stay, answering different questions.
--
-- ON DELETE SET NULL on both new references: removing an image or retiring a
-- team member must never delete published writing. The post falls back to no
-- cover and no byline.
-- ---------------------------------------------------------------------------

CREATE TABLE categories (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The URL segment, /blog?category={slug}. Unique because it addresses.
    slug        text        NOT NULL UNIQUE,
    name        text        NOT NULL DEFAULT '',

    -- Shown on the filtered listing; also the meta description for it, so an
    -- empty one is a thin page rather than a broken one.
    description text        NOT NULL DEFAULT '',

    sort_order  int         NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE  categories             IS
    'Topic vocabulary for posts. Ordered by sort_order, then name.';
COMMENT ON COLUMN categories.description IS
    'Intro copy and meta description for the filtered listing page.';

-- Join table, not a category_id column on posts: a post about e-commerce
-- security is genuinely both, and forcing a single choice would push editors
-- into inventing combination categories.
--
-- CASCADE on both sides is right here and nowhere else in this file — these
-- rows carry no content of their own, so an orphaned pairing is pure garbage.
CREATE TABLE post_categories (
    post_id     bigint NOT NULL REFERENCES posts (id)      ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, category_id)
);

-- The join is read in both directions: post -> its categories when rendering
-- an article, category -> its posts when filtering the listing. The primary
-- key already serves the first; this index serves the second.
CREATE INDEX post_categories_category_idx ON post_categories (category_id);

ALTER TABLE posts
    ADD COLUMN cover_media_id  bigint REFERENCES media (id)        ON DELETE SET NULL,
    ADD COLUMN author_team_id  bigint REFERENCES team_members (id) ON DELETE SET NULL;

CREATE INDEX posts_cover_idx  ON posts (cover_media_id);
CREATE INDEX posts_author_team_idx ON posts (author_team_id);

COMMENT ON COLUMN posts.cover_media_id IS
    'media.id of the cover image. NULL renders the card without a media block.';
COMMENT ON COLUMN posts.author_team_id IS
    'team_members.id of the credited author — an editorial choice, unlike author_id.';

-- --- Backfill --------------------------------------------------------------
-- Every article already carries a tag; without this the four published pieces
-- would come out of the migration uncategorised and the new listing filters
-- would be empty on day one.
--
-- slugify() (inc/sanitize.php) lives in PHP, so the slug is rebuilt in SQL
-- here. It mirrors that function exactly -- lowercase, [^a-z0-9]+ collapsed to a
-- hyphen, then leading and trailing hyphens trimmed -- because a slug written
-- by this backfill and one written later by the admin form address the same
-- kind of thing and must agree on spelling.

INSERT INTO categories (slug, name)
SELECT DISTINCT
       trim(both '-' from regexp_replace(lower(trim(tag)), '[^a-z0-9]+', '-', 'g')),
       trim(tag)
  FROM posts
 WHERE trim(tag) <> ''
ON CONFLICT (slug) DO NOTHING;

INSERT INTO post_categories (post_id, category_id)
SELECT p.id, c.id
  FROM posts p
  JOIN categories c
    ON c.slug = trim(both '-' from regexp_replace(lower(trim(p.tag)), '[^a-z0-9]+', '-', 'g'))
 WHERE trim(p.tag) <> ''
ON CONFLICT DO NOTHING;
