-- ---------------------------------------------------------------------------
-- 009 services table
--
-- Moves the five services out of inc/data/services.php (a seed file that
-- needs a deploy to change) and into the database, editable via admin panel.
-- inc/repo/services.php is already wired for this: uncomment the DB branch
-- inside services_all() once this migration has run.
--
-- The seed file survives as a fallback: the repo falls through to it when the
-- table is empty, so migrating does not require immediately seeding the data.
-- ---------------------------------------------------------------------------

CREATE TABLE services (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          text        NOT NULL UNIQUE,
    title         text        NOT NULL,
    icon          text        NOT NULL DEFAULT 'layers',
    key_name      text        NOT NULL DEFAULT 'web',
    tagline       text        NOT NULL DEFAULT '',
    intro         text        NOT NULL DEFAULT '',
    card          text        NOT NULL DEFAULT '',
    sort_order    int         NOT NULL DEFAULT 0,
    is_published  boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX services_sort      ON services (sort_order, id);
CREATE INDEX services_published ON services (is_published, sort_order);
