<?php
/**
 * PREVIEW SEED — sample content, so the site can be SEEN fully populated.
 *
 * ┌──────────────────────────────────────────────────────────────────────┐
 * │  SAMPLE. Every row here is anonymised preview content written to     │
 * │  show the design with something in it. Nothing is a client claim,    │
 * │  a real person, or a figure anyone has verified. It renders ONLY when │
 * │  PREVIEW_SEED is true (inc/config.local.php) AND no database is       │
 * │  reachable — production with a database never sees this file.        │
 * └──────────────────────────────────────────────────────────────────────┘
 *
 * Shapes match the repositories exactly (inc/repo/content.php, blog.php,
 * blog-post.php), so a template cannot tell a seed row from a database row.
 * The CLI writer inc/tools/seed-preview.php upserts these same arrays into a
 * real database for previewing on a server — with the same warning printed.
 *
 * Images: /uploads/seed-*.png are generated by inc/tools/build-paper.php
 * (monogram portraits on slab texture; plates printed as editorial covers).
 */

return [

    /* ---------------------------------------------------------------- team
       Columns of team_all(): id, name, role, brief, bio, github_url,
       linkedin_url, is_placeholder, photo (uploads filename), photo_alt. */
    'team_members' => [
        [
            'id' => 1, 'name' => 'Aarav Raghunathan', 'role' => 'Founder & Delivery Lead',
            'brief' => 'Runs every engagement end to end — one point of contact, one plan.',
            'bio' => "Aarav started Rafly after five years of watching small businesses pay five vendors to build one thing badly. He scopes every package personally, writes the plan the team works from, and is the person you message when something needs deciding. Before Rafly he led delivery for a mid-size agency's e-commerce practice.",
            'github_url' => '', 'linkedin_url' => 'https://www.linkedin.com/', 'is_placeholder' => 0,
            'photo' => 'seed-team-1.png', 'photo_alt' => 'Aarav Raghunathan',
        ],
        [
            'id' => 2, 'name' => 'Priya Kulkarni', 'role' => 'Lead Engineer',
            'brief' => 'Builds the sites, stores and portals — and keeps them fast.',
            'bio' => "Priya owns the front-end and back-end build on every package: responsive layouts checked at phone widths, integrations confirmed during discovery, and a performance pass before launch rather than after. She has shipped Laravel, WordPress and Shopify builds for retail, healthcare and SaaS clients.",
            'github_url' => 'https://github.com/', 'linkedin_url' => 'https://www.linkedin.com/', 'is_placeholder' => 0,
            'photo' => 'seed-team-2.png', 'photo_alt' => 'Priya Kulkarni',
        ],
        [
            'id' => 3, 'name' => 'Sameer Nair', 'role' => 'Security & Infrastructure',
            'brief' => 'The baseline security review on every build is his.',
            'bio' => "Sameer reviews forms, sessions and access handling on every site before it goes live, sets up monitoring, and runs the hardening work on the security packages. He came from managed hosting, where he spent four years cleaning up after breaches that a baseline review would have prevented.",
            'github_url' => 'https://github.com/', 'linkedin_url' => '', 'is_placeholder' => 0,
            'photo' => 'seed-team-3.png', 'photo_alt' => 'Sameer Nair',
        ],
        [
            'id' => 4, 'name' => 'Meera Joshi', 'role' => 'Content & Brand',
            'brief' => 'Writes the words, plans the calendar, keeps the voice consistent.',
            'bio' => "Meera turns a discovery call into a content plan: site copy, product descriptions, articles and the social calendar, all in one voice. She edits everything the team publishes for clients and insists on plain language over jargon — including in our own proposals.",
            'github_url' => '', 'linkedin_url' => 'https://www.linkedin.com/', 'is_placeholder' => 0,
            'photo' => 'seed-team-4.png', 'photo_alt' => 'Meera Joshi',
        ],
        [
            'id' => 5, 'name' => 'Rohan Verma', 'role' => 'Growth & Analytics',
            'brief' => 'Paid, organic and the numbers that say which one is working.',
            'bio' => "Rohan runs the marketing side of every package — search and social campaigns, analytics setup, and the monthly readout in plain language. He would rather turn a campaign off than keep spending on one the data does not support, which is why the readouts are honest.",
            'github_url' => '', 'linkedin_url' => 'https://www.linkedin.com/', 'is_placeholder' => 0,
            'photo' => 'seed-team-5.png', 'photo_alt' => 'Rohan Verma',
        ],
    ],

    /* -------------------------------------------------------- case studies
       Columns of case_studies_all(): client_name, sector, problem, action,
       metric_value, metric_label, is_placeholder, tags. Client names are
       anonymised descriptors on purpose. */
    'case_studies' => [
        [
            'client_name' => 'Regional furniture retailer', 'sector' => 'E-commerce',
            'problem' => "A five-year-old store on a theme nobody could edit, a checkout that failed on phones, and product listings written for a catalogue rather than a search box. Three vendors, none of whom would touch the others' work.",
            'action' => "Rebuilt the store on a maintainable platform, rewrote 240 listings for clarity and search, moved payments and shipping to supported integrations, and ran a baseline security review before launch. One team, one plan, one number.",
            'metric_value' => '2.4x', 'metric_label' => 'mobile checkout completion', 'is_placeholder' => 0,
            'tags' => 'Shopify, Product content, Payments, Security review',
        ],
        [
            'client_name' => 'Independent dental group', 'sector' => 'Healthcare',
            'problem' => "Four clinic websites built at four different times, an appointment form that emailed a shared inbox, and no idea which campaigns were bringing patients in.",
            'action' => "One site for four locations, an appointment flow that lands in the practice system, search campaigns with call tracking per clinic, and a monthly readout the practice manager actually reads.",
            'metric_value' => '61%', 'metric_label' => 'more booked appointments in 90 days', 'is_placeholder' => 0,
            'tags' => 'Web development, Search ads, Analytics, Content',
        ],
        [
            'client_name' => 'B2B logistics software startup', 'sector' => 'SaaS',
            'problem' => "A product ahead of its website: a one-page site from the seed round, no articles, no case studies, and demo requests arriving as bare emails with no context.",
            'action' => "Marketing site with a real information architecture, a demo-request flow into the CRM, a content calendar the founders can keep up with, and security headers and access handling reviewed as part of the build.",
            'metric_value' => '3x', 'metric_label' => 'qualified demo requests per month', 'is_placeholder' => 0,
            'tags' => 'Web development, Content, CRM integration, Security',
        ],
        [
            'client_name' => 'Boutique hotel', 'sector' => 'Hospitality',
            'problem' => "Bookings leaking to third-party platforms at 18% commission, a gallery of photographs that took eleven seconds to load, and social accounts nobody had posted to since the pandemic.",
            'action' => "Direct-booking site with a fast gallery, campaigns pointed at direct booking, a content plan the front desk can run, and monitoring so the site does not go down on a holiday weekend.",
            'metric_value' => '38%', 'metric_label' => 'of bookings now direct', 'is_placeholder' => 0,
            'tags' => 'Web development, Performance, Social content, Marketing',
        ],
        [
            'client_name' => 'Professional training institute', 'sector' => 'Education',
            'problem' => "Course pages that could not be updated without a developer, a payment gateway that failed silently, and enquiries answered days late.",
            'action' => "Editable course catalogue, working payments with receipts, an enquiry flow with response tracking, and a search campaign for the two courses with real margin.",
            'metric_value' => '4 days', 'metric_label' => 'to 4 hours median enquiry response', 'is_placeholder' => 0,
            'tags' => 'Web development, Payments, Marketing, Support',
        ],
        [
            'client_name' => 'Family-run manufacturing firm', 'sector' => 'Manufacturing',
            'problem' => "A brochure site from 2014, a product catalogue in a PDF, and dealer enquiries lost in personal inboxes.",
            'action' => "Product catalogue on the site with dealer enquiry routing, a plain-language content refresh, and a security review of the ageing hosting before anything else was touched.",
            'metric_value' => '120+', 'metric_label' => 'dealer enquiries routed in the first quarter', 'is_placeholder' => 0,
            'tags' => 'Web development, Content, Security, Support',
        ],
    ],

    /* -------------------------------------------------------- testimonials
       Columns of testimonials_all(): quote, author_name, author_role,
       author_company, consent_given, is_placeholder. */
    'testimonials' => [
        [
            'quote' => "For the first time we have one person to call. The store, the ads and the content stopped contradicting each other the month Rafly took over.",
            'author_name' => 'Kavita S.', 'author_role' => 'Owner', 'author_company' => 'Regional furniture retailer',
            'consent_given' => 1, 'is_placeholder' => 0,
        ],
        [
            'quote' => "The monthly readout is the only marketing report I have ever read to the end. It says what worked, what did not, and what they are changing.",
            'author_name' => 'Dr. Arjun M.', 'author_role' => 'Practice Manager', 'author_company' => 'Independent dental group',
            'consent_given' => 1, 'is_placeholder' => 0,
        ],
        [
            'quote' => "We got a scope, a number and a date. Then we got exactly that. I did not know agencies did that.",
            'author_name' => 'Neha T.', 'author_role' => 'Co-founder', 'author_company' => 'B2B logistics software startup',
            'consent_given' => 1, 'is_placeholder' => 0,
        ],
        [
            'quote' => "The security review found two things our previous host had missed for years. That alone paid for the package.",
            'author_name' => 'Vikram D.', 'author_role' => 'Director', 'author_company' => 'Family-run manufacturing firm',
            'consent_given' => 1, 'is_placeholder' => 0,
        ],
    ],

    /* ------------------------------------------------------------ blog
       Columns of the blog.php list query: id, slug, title, tag, excerpt,
       published_at, read_minutes, cover, cover_alt, author_name, author_role,
       author_photo, category_name. blog-post.php adds meta_desc, body,
       updated_at, author_id. Bodies come from inc/tools/seed-posts.php (the
       four articles already written for this site) — see seed_preview_posts(). */
    'categories' => [
        ['id' => 1, 'slug' => 'strategy',   'name' => 'Strategy',   'description' => 'How to think about digital growth as one system rather than a list of vendors.', 'sort_order' => 1],
        ['id' => 2, 'slug' => 'security',   'name' => 'Security',   'description' => 'The baseline every small business site should meet, in plain language.', 'sort_order' => 2],
        ['id' => 3, 'slug' => 'e-commerce', 'name' => 'E-commerce', 'description' => 'Stores that convert: listings, checkout, speed and the ads that follow.', 'sort_order' => 3],
        ['id' => 4, 'slug' => 'automation', 'name' => 'Automation', 'description' => 'Where AI and automation actually save a small team time.', 'sort_order' => 4],
    ],
    'posts_meta' => [
        // slug => overrides for the four seed-posts.php articles
        'bundled-packages-vs-freelancers'          => ['id' => 1, 'published_at' => '2026-07-02 09:00:00', 'cover' => 'seed-cover-01.png', 'category' => 'strategy',   'author' => 1],
        'small-business-website-security-basics'   => ['id' => 2, 'published_at' => '2026-07-16 09:00:00', 'cover' => 'seed-cover-02.png', 'category' => 'security',   'author' => 3],
        'clean-product-listings-before-ads'        => ['id' => 3, 'published_at' => '2026-07-30 09:00:00', 'cover' => 'seed-cover-03.png', 'category' => 'e-commerce', 'author' => 4],
        'ai-automation-small-business-workflows'   => ['id' => 4, 'published_at' => '2026-08-11 09:00:00', 'cover' => 'seed-cover-04.png', 'category' => 'automation', 'author' => 2],
    ],

    /* ------------------------------------------------------------ settings
       Only the keys the public site reads. Trust claims are marked verified
       here because this is a preview of the design, not a claim. */
    'settings' => [
        'trust.projects.value'      => '120',
        'trust.projects.verified'   => '1',
        'trust.satisfaction.value'  => '98',
        'trust.satisfaction.verified' => '1',
        'contact.address'           => 'Bengaluru, Karnataka',
        'contact.hours'             => 'Mon–Sat, 10:00–19:00 IST',
    ],
];
